# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_NPY=110  CONDA_PY=34
    - CONDA_NPY=111  CONDA_PY=34
    - CONDA_NPY=110  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZXdhLfivM0vgxK0kk+tT/phpK5OyjtyWxsNtf97fIgPEugeqKGa+HCMW/K2vxmvEiKTk355t4lRGF/DLD6zZIFz8P15PnxHbh/D0H0XoJrHcHGZhmIJHTBbzLLq5WQ/2utF0IgES1O3FDyQlJlVQLPvB5eUiAm/WfuHZDCjDdAsWQvsFc02t5LyFf2XJRiDskbTgOcxl5aSoMMYlQ9oCKDFDgXnmLo193HI/Rfp9oB2eGYYa4bsOKyI/teszQibZ8SRUNI+CNRE0AYKfcecBF/p/g886dLG73LNC9pOq6mCbCXCJJdVT+DznI2QEeJ9IKLBckQ14Yh6uElhiSof/bqdqVL889UczVN3PmJ69ASPl1d4Tdpy1wFoPvH0AF/zfnW/LmW9tyRlGE4HwsQC0Q7KJBuZAYMJYkArQjfZAy/N1F2SAQqsEJ3NfO4EQzrD2HxElQbzaMXrfk6oAV0qP0lYX4f3meLOLNnolT7X3lL3Pk57KfT8imY4z5RjF1qOPf195+ePwpQgrOFji9A5egQxx/Hyr+AgWlBm7F8I/e0zEPzcU5JfKmTu1TfLtEKIV189upPkUHfpprRFr25OSvoR3o0x3so2qBVAlOxS8fmVGrJJhprYAexLoK3VYCXp+GyKlVvWcq5d/XLayPsf0v1XdqSWkb/54ZQS9JR/Hj7U="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
