travis:
  secure:
    BINSTAR_TOKEN: ZXdhLfivM0vgxK0kk+tT/phpK5OyjtyWxsNtf97fIgPEugeqKGa+HCMW/K2vxmvEiKTk355t4lRGF/DLD6zZIFz8P15PnxHbh/D0H0XoJrHcHGZhmIJHTBbzLLq5WQ/2utF0IgES1O3FDyQlJlVQLPvB5eUiAm/WfuHZDCjDdAsWQvsFc02t5LyFf2XJRiDskbTgOcxl5aSoMMYlQ9oCKDFDgXnmLo193HI/Rfp9oB2eGYYa4bsOKyI/teszQibZ8SRUNI+CNRE0AYKfcecBF/p/g886dLG73LNC9pOq6mCbCXCJJdVT+DznI2QEeJ9IKLBckQ14Yh6uElhiSof/bqdqVL889UczVN3PmJ69ASPl1d4Tdpy1wFoPvH0AF/zfnW/LmW9tyRlGE4HwsQC0Q7KJBuZAYMJYkArQjfZAy/N1F2SAQqsEJ3NfO4EQzrD2HxElQbzaMXrfk6oAV0qP0lYX4f3meLOLNnolT7X3lL3Pk57KfT8imY4z5RjF1qOPf195+ePwpQgrOFji9A5egQxx/Hyr+AgWlBm7F8I/e0zEPzcU5JfKmTu1TfLtEKIV189upPkUHfpprRFr25OSvoR3o0x3so2qBVAlOxS8fmVGrJJhprYAexLoK3VYCXp+GyKlVvWcq5d/XLayPsf0v1XdqSWkb/54ZQS9JR/Hj7U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
